### ISSUE TITLE
Linux client display image missing.

### ISSUE THREAD

**Issue by FXBOY4EVA** [trango-io/trango-self-hosted#1]
/app/img/coming-soon/ contains client display images for Android, iOS, Mac and Windows.

Linux is missing.

When a linux client opens application (tested using firefox, chromium and Brave), windows image appears to represent client.

Otherwise, excellent project, thank you!

**Comment by mmurtaznaqvi** [comment]
Fixed in 4dbc86a6f454c95b7547866d57dff4cbb51a0f32 thanks for reporting.

**Comment by gigawatts** [comment]
Similarly, on a Chromebook (a Pixelbook, Chrome Browser), I see this icon representing itself:
![image](https://user-images.githubusercontent.com/1954516/110256762-3f44e600-7f60-11eb-8ee3-e13b61cdfbe6.png)

![image](https://user-images.githubusercontent.com/1954516/110256750-30f6ca00-7f60-11eb-9830-71d2187d03f8.png)

Interestingly, that same Chromebook device shows a Mac symbol when I connect to the web app from my Android phone (Chrome).

I'm using the latest version of this docker container, for reference: https://hub.docker.com/r/tak786/trango-self-hosted
