### ISSUE TITLE
iOS Consistent Dicovery

### ISSUE THREAD

**Issue by MaestroJAL** [trango-io/trango-self-hosted#2]
Hi! Great work on Trango. I can see its usefulness. I'm having a problem consistently seeing devices on our home network and am trying to troubleshoot. Here's my setup: Trango via Docker being reverse proxied via Nginx at a custom domain. I've upgraded my Nginx connection (websockets). I am using Safari only on all devices (tried Firefox on the Mac but the video quality tanked). Sometimes, I can refresh and see the other devices. Other times, no. When devices can be seen, they connect just fine. Any ideas?

**Comment by mmurtaznaqvi** [comment]
Hello! please verify if you are having the same problem on our web version [https://web.trango.io](url). Also, there is an idle timeout which is 20 minutes for inactive connections in the discovery server so can remove it if you want connections to be idle for a long time. Also, verify if upgraded NGINX connection (WebSockets) has proxy_read_timeout which should have a large value.
![image](https://user-images.githubusercontent.com/39719933/87502743-da104d80-c67b-11ea-87ab-0f7d5a04b4af.png)

**Comment by MaestroJAL** [comment]
Your site at web.trango.io works very well on both desktop and mobile devices. I notice that my desktop Safari keeps flashing "Reconnecting". I must have something wrong in the nginx proxy configuration. Do you possibly have a working example for nginx?

**Comment by mmurtaznaqvi** [comment]
Safari does not allow us to connect to WebSocket connections which are using self-signed certificates if you are deploying it on your custom domain replace certificates with trusted ones and rebuild the docker image using dockerfile provided. This will resolve problems on IOS for mac you can add the provided certificate into your trust store.

**Comment by MaestroJAL** [comment]
I have a valid wildcard SSL certificate and updated the Dockerfile with the proper certificates and built the image. Still unable to connect. I'm going to mess around with some things and see if I can get it to work. In the meantime, if you have any more suggestions, please shoot them my way!

**Comment by mmurtaznaqvi** [comment]
I have tested it on our testing environment and it is working fine for IOS. I think so your certificates are not properly configured in ssl.conf file of NGINX. Please ensure that names are the same as certificates in ssl.conf.
![image](https://user-images.githubusercontent.com/39719933/87750083-e5967c80-c813-11ea-9262-951feaf43d6f.png)
