### ISSUE TITLE
Port 443 seems hardcoded

### ISSUE THREAD

**Issue by nachilau** [trango-io/trango-self-hosted#3]
Hello, thanks for the good work! However, when I try to using another port rather than 443 to start the docker container, the app didn't work. Is there any way to make it accept other external port rather than 443?

This is the command I used to run my container
sudo docker container run -d -p 1001:80 -p 1002:443 --name trango tak786/trango-self-hosted

Thanks!

**Comment by mmurtaznaqvi** [comment]
Hi, in docker image nginx is used as a web server and we are redirecting traffic to port 443 inside default conf file you can remove this redirect to make it work.

**Comment by mmurtaznaqvi** [comment]
Also, WebRTC does not work without Https so try accessing https://<your_ip>:1002 this will work.

**Comment by nachilau** [comment]
Cool, thanks it works, I make a change in here
![image](https://user-images.githubusercontent.com/5043145/87611796-cc7bb780-c6bd-11ea-947f-dd7cf80656d2.png)
or reroute all access to the https port (in my case 1002), everything works now
